# Fly.io configuration for Olive Marketing Intelligence
# Generated for deployment with persistent storage support

app = "olive-marketing-intelligence"
primary_region = "sjc"  # San Jose, California - good for US users

[build]

[deploy]
  release_command = "python -c 'from startup_with_db import generate_database; generate_database()'"

[env]
  FLASK_ENV = "production"
  FLASK_DEBUG = "0"
  USE_ML_MODELS = "1"
  DATABASE_URL = "sqlite:///app/instance/marketing.db"
  CORS_ORIGINS = "https://your-frontend.vercel.app,http://localhost:3000"
  # Generate database at runtime since upload failed
  # SKIP_DB_GENERATION = "1"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30m"
    interval = "60s"
    method = "GET"
    timeout = "10s"
    path = "/api/health"

# [mounts]
#   source = "database_vol"
#   destination = "/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
