# fly.toml app configuration file generated for olive-marketing-intelligence on 2025-10-22T21:09:25-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'olive-marketing-intelligence'
primary_region = 'sjc'

[build]

[env]
  CORS_ORIGINS = 'https://your-frontend.vercel.app,http://localhost:3000'
  DATABASE_URL = 'sqlite:///app/instance/marketing.db'
  FLASK_DEBUG = '0'
  FLASK_ENV = 'production'
  USE_ML_MODELS = '1'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '10s'
    grace_period = '30m0s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
